### ISSUE TITLE
Wrong OAuth Provider URLs (Keycloak) generated when provider uses SSL

### ISSUE THREAD

**Issue by chdudek** [stackabletech/superset-operator#534]
### Affected Stackable version

24.3

### Affected Apache Superset version

3.1.0

### Current and expected behavior

**Current behavior:**
Given the following AuthenticationClass configuration:

```yaml
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: <keycloak_service_host>
      port: 443                    
      rootPath: /realms/dive   
      scopes:
      - email
      - openid
      - profile
      principalClaim: preferred_username
```
The following Superset configuration is created in `/stackable/config/superset_config.py`:
```python
# (...)
OAUTH_PROVIDERS = [
  { 'name': 'keycloak',
    'icon': 'fa-key',
    'token_key': 'access_token',
    'remote_app': {
      'client_id': os.environ.get('OIDC_F5EAEA3B99E6BD19_CLIENT_ID'),
      'client_secret': os.environ.get('OIDC_F5EAEA3B99E6BD19_CLIENT_SECRET'),
      'client_kwargs': {
        'scope': 'email openid profile'
      },
      'api_base_url': 'http://<keycloak_service_host>:443/realms/dive/protocol/',
      'server_metadata_url': 'http://<keycloak_service_host>:443/realms/dive/.well-known/openid-configuration',
    },
  }
]
# (...)
```
Host and port are used "as is" to create a `http://` URL. With this configuration a connection to the Keycloak server is not possible.

**Expected behavior:**
The following configuration should be created in `/stackable/config/superset_config.py`:
```python
# (...)
OAUTH_PROVIDERS = [
  { 'name': 'keycloak',
    'icon': 'fa-key',
    'token_key': 'access_token',
    'remote_app': {
      'client_id': os.environ.get('OIDC_F5EAEA3B99E6BD19_CLIENT_ID'),
      'client_secret': os.environ.get('OIDC_F5EAEA3B99E6BD19_CLIENT_SECRET'),
      'client_kwargs': {
        'scope': 'email openid profile'
      },
      'api_base_url': 'https://<keycloak_service_host>/realms/dive/protocol/',
      'server_metadata_url': 'https://<keycloak_service_host>/realms/dive/.well-known/openid-configuration',
    },
  }
]
# (...)
```
Given port 443, the URL should start with `https://`.

### Possible solution

As it might be possible that a non-standard port is used for the Keycloak service is used I would propose that a new configuration option `protocol` should be added to AuthenticationClass:
```yaml
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: <keycloak_service_host>
      port: 12345
      protocol: https # defaults to `http`
      rootPath: /realms/dive   
      scopes:
      - email
      - openid
      - profile
      principalClaim: preferred_username
```

### Additional context

As a workaround we fixed the problem by overwriting the configuration in our `superset.yaml`:

```yaml
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 3.1.0
  clusterConfig:
    listenerClass: external-unstable
    credentialsSecret: superset-credentials
    mapboxSecret: superset-mapbox-api-key
    vectorAggregatorConfigMapName: vector-aggregator-discovery
    authentication:
    - authenticationClass: keycloak
      syncRolesAt: Login
      oidc:
        clientCredentialsSecret: superset-keycloak-client
      userRegistrationRole: "Admin"
      userRegistration: true
  nodes:
    roleGroups:
      default:
        replicas: 1
        config:
          logging:
            enableVectorAgent: true
        configOverrides:
          superset_config.py:
            OAUTH_PROVIDERS: |-
              [
                { 'name': 'keycloak',
                  'icon': 'fa-key',
                  'token_key': 'access_token',
                  'remote_app': {
                    'client_id': os.environ.get('OIDC_F5EAEA3B99E6BD19_CLIENT_ID'),
                    'client_secret': os.environ.get('OIDC_F5EAEA3B99E6BD19_CLIENT_SECRET'),
                    'client_kwargs': {
                      'scope': 'email openid profile'
                    },
                    'api_base_url': 'https://<keycloak_service_host>/realms/dive/protocol/',
                    'server_metadata_url': 'https://<keycloak_service_host>/realms/dive/.well-known/openid-configuration',
                  },
                }
              ]
```

### Environment

```
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+rke2r1
```

### Would you like to work on fixing this bug?

maybe

**Comment by sbernauer** [comment]
Hi @chdudek thanks for raising this well-written issue!

There is actually a field `spec.provider.oidc.tls`, where you can state that TLS should be used.
You can have a look at our [CRD docs](https://crds.stackable.tech/24.7.0/authentication.stackable.tech/authenticationclass/v1alpha1/) or execute `kubectl explain authenticationclass.spec.provider.oidc` to get some details.
TLS server verification is documented [here](https://docs.stackable.tech/home/nightly/concepts/tls-server-verification).

Assuming your Keycloak has a globally trusted cert you could do

```yaml
spec:
  provider:
    oidc:
      tls:
        verification:
          server:
            caCert:
              webPki: {}
```

I created https://github.com/stackabletech/documentation/issues/654 to mention TLS in the docs.

I hope this helps, please feel free to reach out in case you run into problems!
